### ISSUE TITLE
New version with "Fix deprecated uses of Redis#pipelined"

### ISSUE THREAD

**Issue by andredurao** [sidekiq-scheduler/sidekiq-scheduler#358]
Hi, guys. 1st I'd like to thanks for work and dedication.

I've noticed that you already fixed the redis pipelined warning messages in [this commit](https://github.com/moove-it/sidekiq-scheduler/commit/bc2eaf3d69d04420490e132f068c0a29e99599da)

Do you plan do release a new version including this fix?

**Comment by marcelolx** [comment]
Hey @andredurao, we plan to release a fix once the fix for this issue is also made https://github.com/moove-it/sidekiq-scheduler/issues/345

I'm going to take some time this month to work on it. While this doesn't happen you can point in your gemfile to the main branch of this repo.

**Comment by marcelolx** [comment]
hey @andredurao, 3.2.0 has been released with the fix for this https://github.com/moove-it/sidekiq-scheduler/blob/v3-stable/CHANGELOG.md

I've also released v4.0.0.alpha1 https://github.com/moove-it/sidekiq-scheduler/blob/v4.0.0.alpha1/CHANGELOG.md to be tested by the community.
