### ISSUE TITLE
When use aliyun redis cluster, raise  all the keys that the script uses should be passed using the KEYS arrayr

### ISSUE THREAD

**Issue by tianlu1677** [sidekiq-scheduler/sidekiq-scheduler#359]
-ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array

[link](https://developer.aliyun.com/article/645851)

**Comment by marcelolx** [comment]
@tianlu1677 I need more context to understand what is the problem. A sample app that reproduces the problem would be welcome
