### ISSUE TITLE
Possible issue with a rails app in docker using sidekiq-scheduler

### ISSUE THREAD

**Issue by benbws** [sidekiq-scheduler/sidekiq-scheduler#405]
I'm getting an odd error when running a fairly standard Rails app within a docker container:

```
app_1            | 00:27:48 sk.1   | 2022-09-09T23:27:48.156Z pid=14 tid=53m WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
app_1            | 00:27:48 sk.1   | 2022-09-09T23:27:48.156Z pid=14 tid=53m WARN: TypeError: Unsupported command argument type: EtOrbi::EoTime
app_1            | 00:27:48 sk.1   | 2022-09-09T23:27:48.156Z pid=14 tid=53m WARN: /usr/local/bundle/gems/redis-client-0.8.0/lib/redis_client/command_builder.rb:37:in `block in generate'
```

The app deploys to Heroku without any issue and all the scheduled tasks set up without issue and execute without issue. I can also run the app on my Windows host machine which has Ubuntu/Ruby/etc set up via WSL - again literally no issues with sidekiq or sidekiq-scheduler.

However, as soon as the app is put into a docker container (I've tried a few different images, official ruby, ubuntu with manual ruby install etc) it fails every time at the point where it attempts to load the scheduled jobs in.

Happy to provide more logs or details of the set up if it would help someone shed any light on this.

**Comment by marcelolx** [comment]
I think this PR fixes your problem https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/404 (at least seems related with Redis 5)

Try to point sidekiq-scheduler in your Gemfile to the master branch, just to see if it keeps happening

**Comment by benbws** [comment]
It does indeed fix the error, thanks for your help.

**Comment by itsNikolay** [comment]
you need to downgrade sidekiq to version `6.5.6` https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/406#issuecomment-1248577817
