### ISSUE TITLE
4.0.4 tag to support sidekiq 7+

### ISSUE THREAD

**Issue by reaper** [sidekiq-scheduler/sidekiq-scheduler#413]
Hi, just asking for your next tag, do you intent to do it shortly ? Didn't see any commit since a month and tests are passing with sidekiq 7 and redis 5. Thanks !

**Comment by marcelolx** [comment]
@reaper https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/409#issuecomment-1303233347

**Comment by marcelolx** [comment]
If you want to use sidekiq-scheduler with Sidekiq 7, please use it the suggested way in my linked comment, we want to get https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/412 merged into master before we make a release.

**Comment by marcelolx** [comment]
btw @reaper, we have released a beta version of sidekiq-scheduler with support for Sidekiq 7 https://github.com/sidekiq-scheduler/sidekiq-scheduler/releases/tag/v5.0.0.beta1
