### ISSUE TITLE
404 for sidekiq/stylesheets-scheduler/recurring_jobs.css

### ISSUE THREAD

**Issue by RobsonKing** [sidekiq-scheduler/sidekiq-scheduler#415]
Using:

sidekiq (6.5.8)
sidekiq-pro (5.5.8)
sidekiq-scheduler (4.0.3)

When I try and view Sidekiq Web UI, the _Recurring Jobs_ tab loads, but the css file 404s

![_DEVELOPMENT__Sidekiq_Pro](https://user-images.githubusercontent.com/7375349/208721873-87c0799f-a234-41d8-8045-043e62b7268b.png)

I found this pr https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/394 where the path was renamed to sidekiq/stylesheets-scheduler/recurring_jobs.css and that is what I am trying to fetch.

I tried serving some of my own css out of my own asset directory and found:

![sidekiq_rb_—_atvenu__SSH__rmk1_](https://user-images.githubusercontent.com/7375349/208723383-2d102232-4ffc-4a51-b129-bc07339ab40a.png)

It seems like any path that starts with `/stylesheets `will not work?

**Comment by marcelolx** [comment]
I think this has something to do with your application, if you clone this repo https://github.com/sidekiq-scheduler/sample-rails locally and run

```sh
bundle install
yarn install
```

and then run

```sh
bin/rails s
```

and access `localhost:3000/sidekiq/recurring-jobs`, does it load the stylesheets? At least for me, it works

![image](https://user-images.githubusercontent.com/20196775/208729407-2c7f0856-1df4-4a63-9f5e-97a040a8d3ed.png)

**Comment by RobsonKing** [comment]
Thanks so much for the sample project!  I was able to modify it and reproduce my problem on an older version of rails (5.1.6.2🤮 ).  If anyone else runs into this, the problem was and old version of rack

rack 2.1.4 exhibits this behaviour
rack 2.2.4 works

**Comment by marcelolx** [comment]
Happy to know you were able to find out the root of the problem!
