### ISSUE TITLE
I am not able to make SFTP connection through my worker in prod environment

### ISSUE THREAD

**Issue by shilpi230** [sidekiq-scheduler/sidekiq-scheduler#422]
I have service class which makes a connection through SFTP and uploads the file, this service class gets called from one of the worker. When I directly call the service I am my code works fine, but when I call it through worker, connection is not getting established. And this behaviour is only happening in Prod environment in local it works fine.

**Comment by marcelolx** [comment]
@shilpi230 I don't think sidekiq-scheduler would have anything to do with it not connecting to the SFTP server. If you're using sidekiq-scheduler to run the job every specific time and the jobs are being enqueued and runs at the defined time, then it means sidekiq-scheduler has done what it proposes to do, which is to schedule jobs based on the cron defined for them. 

If when the job is running, it is not able to establish a connection with the SFTP server, then it is probably another problem that has nothing to do with sidekiq-scheduler.

I'll close this issue, if you think it is a problem with sidekiq-scheduler, I'm happy to help if more information would be provided.
