### ISSUE TITLE
Documentation issue with scheduler nesting 

### ISSUE THREAD

**Issue by neeko99** [sidekiq-scheduler/sidekiq-scheduler#423]
Looks like theres a small bug in the documentation vs the workings of the code.  The usage yml suggests you should have 

```
:scheduler: 
  :schedule: 
```

https://github.com/sidekiq-scheduler/sidekiq-scheduler#hello-world

```
# config/sidekiq.yml

:scheduler:
  :schedule:
    hello_world:
      cron: '0 * * * * *'   # Runs once per minute
      class: HelloWorld
```

However the :scheduler:  module appears to prevent the scheduler from loading with `Schedule empty! Set Sidekiq.schedule`

**Comment by marcelolx** [comment]
@neeko99 are you using `Sidekiq.configure_embed` to run sidekiq? If so, check https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/419, we don't support sidekiq in that mode, yet

**Comment by neeko99** [comment]
Sorry chap,  My mistake.

i've pulled an older version 🤦.
