### ISSUE TITLE
Move away from deprecated Redis commands

### ISSUE THREAD

**Issue by fmichaut-diff** [sidekiq-scheduler/sidekiq-scheduler#441]
Currently getting this warning : 
```
[sidekiq#5788] Redis has deprecated the `zrangebyscore`command, called at ["~/.rvm/gems/ruby-3.2.0/gems/sidekiq-scheduler-5.0.2/lib/sidekiq-scheduler/redis_manager.rb:109:in `block in get_schedule_changes'"]
```

We should move away from deprecated redis commands.

Sidekiq did it already, might contain useful pointers to help the transition : 
- https://github.com/sidekiq/sidekiq/issues/5788
- https://github.com/sidekiq/sidekiq/commit/1aca434e5cd830cbd0020f1f82ef3a3cb6b2d477

**Comment by marcelolx** [comment]
We have already migrated away https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/437, I just didn't have time to push a release. I will keep the issue open until I push the release
