### ISSUE TITLE
Recommend Sidekiq::Job instead of Sidekiq::Worker

### ISSUE THREAD

**Issue by jrmhaig** [sidekiq-scheduler/sidekiq-scheduler#456]
Sidekiq 7 has deprecated `Sidekiq::Worker` in favour of `Sidekiq::Job` and I believe that `Sidekiq::Job` was first introduced as an alias in 6.3. The documentation for `sidekiq-scheduler` indicates that `Sidekiq::Worker` should be used. I appreciate that `sidekiq-scheduler` needs to support earlier version of `sidekiq` so perhaps there could be a note added to indicate that `Sidekiq::Job` is recommended for more recent version.

**Comment by marcelolx** [comment]
Yeah, I agree with you. Feel free to send a PR with the changes if you are willing to; Otherwise, I will look into it when I have some free time
