### ISSUE TITLE
Implement `to_hash` in SidekiqScheduler::Manager to avoid Stack level too deep error.

### ISSUE THREAD

**Issue by yiyenene** [sidekiq-scheduler/sidekiq-scheduler#468]
Hi.

I faced Stack level too deep error when sidekiq dumps log of its config.
It was caused by my logger using ActiveSupport's `as_json`.

This gem sets `SidekiqScheduler::Manager` instance to sidekiq's config and Manager instance has sidekiq's config inside through SidekiqManager::Config instance. 
There is a circular reference. (and also is in the Rufus::Scheduler instance.)

ActiveSupoort's `as_json` traverses `instance_values` unless it responds to `to_hash`. 
So, how about implement `to_hash` in SidekiqScheduler::Manager to avoid unintended exposing instance values and stack level too deep error ?

Would it be alright if I create the PR ?

ref 
- https://github.com/rails/rails/issues/51626
- https://github.com/sidekiq/sidekiq/issues/5920

I apologize if my English seems rude.

**Comment by marcelolx** [comment]
@yiyenene, thanks for the report; I think this might also be related to this issue: https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/462 — A PR is definitely welcome, and your English isn't rude!

**Comment by yiyenene** [comment]
Thank you for merging and fixing typo 🙇
