### ISSUE TITLE
Dark Mode looking funky in 5.0.4

### ISSUE THREAD

**Issue by OskarEichler** [sidekiq-scheduler/sidekiq-scheduler#475]
![Screenshot 2024-07-04 at 17 07 07](https://github.com/sidekiq-scheduler/sidekiq-scheduler/assets/62393985/a87da22c-3802-402d-9229-600c0233aadc)

**Comment by marcelolx** [comment]
Could you explain which version of Sidekiq you are running + ruby?

I wonder if it is related to this https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/472

**Comment by OskarEichler** [comment]
Latest version of Sidekiq and Ruby 3.2.1

**Comment by marcelolx** [comment]
@t27duck could you take a look into this when you have time? I guess you might know better than me what might be going on

**Comment by t27duck** [comment]
Linked PR should have the fix. I tested it against a one-off Rails app with Sidekiq 7.3 and the latest 7.2 with browser cache disabled to make sure the CSS was actually being requested.

**Comment by t27duck** [comment]
Forgot I have push privileges so I just merged it in. Until a new release is rolled, linking the gem to the `master` branch will get you  the styles back.

Verified the change works on a production app I just deployed that linked the gem to `master`.

**Comment by marcelolx** [comment]
Thanks @t27duck! [v5.0.5](https://github.com/sidekiq-scheduler/sidekiq-scheduler/releases/tag/v5.0.5) released!

**Comment by OskarEichler** [comment]
Epic!! Thank you gents!
