### ISSUE TITLE
Keep testing against 2.7 and 3.0 in version 5.0.x to avoid breaking changes at patch level

### ISSUE THREAD

**Issue by tagliala** [sidekiq-scheduler/sidekiq-scheduler#477]
Hello,

this change

https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/472/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR14

introduced in #472 may break backward compatibility in a patch release if someone starts using new Ruby 3.1 features, like `Array#intersect?` https://rubyapi.org/3.1/o/array#method-i-intersect-3F

This happened in the past, especially between 2.2 and 2.3 and the safe navigation operation or the squiggly heredoc, so some gems introduced breaking changes at patch level without noticing, having the developers to lock their gemfile to 'x.y.z', which is ok since it is a "legacy app" but can be avoided

This is one of the latest examples I remember: thoughtbot/factory_bot#1614, but there are many others

**Comment by marcelolx** [comment]
That sounds reasonable, could you put a PR together for that @tagliala?

**Comment by tagliala** [comment]
@marcelolx done at #486, but I guess there is an issue with Sidekiq so specs are failing against 2.7

**Comment by tagliala** [comment]
Filled in an issue on sidekiq: sidekiq/sidekiq#6371

**Comment by tagliala** [comment]
https://github.com/sidekiq/sidekiq/issues/6371 has been fixed on main, waiting for 7.3.1
